version: '3'
services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    working_dir: /app
    command: node index.js

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    working_dir: /app
    command: npm run dev
